info:
  namespace: "lion_emojis"
font_images:
  peepohappy:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/peepohappy"
    scale_ratio: 9
    y_position: 8
  peepoclown:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/peepoclown"
    scale_ratio: 9
    y_position: 8
  peepohug:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/peepohug"
    scale_ratio: 9
    y_position: 8
  peepoblush:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/peepoblush"
    scale_ratio: 9
    y_position: 8
  peepowtf:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/peepowtf"
    scale_ratio: 9
    y_position: 8
  catblush:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/catblush"
    scale_ratio: 9
    y_position: 8
  ez:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/ezf"
    scale_ratio: 9
    y_position: 8
  kekw:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/kekw"
    scale_ratio: 9
    y_position: 8
  pepehands:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/pepehands"
    scale_ratio: 9
    y_position: 8
  monkahmm:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/monkahmm"
    scale_ratio: 9
    y_position: 8
  pepelaugh:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/pepelaugh"
    scale_ratio: 9
    y_position: 8
  sadge:
    permission: "itemsadder.emoji.use"
    show_in_gui: true
    path: "font/emoji/sadge"
    scale_ratio: 9
    y_position: 8